"""
elevenlabs_to_did.py
--------------------
End‑to‑end pipeline: TEXT  ➜  ElevenLabs TTS  ➜  D‑ID audio upload  ➜  D‑ID video
"""

import time
import requests
from requests.auth import HTTPBasicAuth
from typing import Tuple

# -------------------------------------------------------------------
# 🔒  INSERT YOUR CREDENTIALS HERE
# -------------------------------------------------------------------
ELEVEN_API_KEY   = "sk_593f3748e11c38548bc0f4d78d23de02f393da80d23e2f06"                 # e.g. "api_key_xxxxxxxxx"
ELEVEN_VOICE_ID  = "21m00Tcm4TlvDq8ikWAM"                    # Example: "Rachel" voice

DID_USERNAME     = "YWJkdWxsYWhkb3RuZXQyMEBnbWFpbC5jb20"                   # left part of the API‑only pair
DID_PASSWORD     = "EGWni8AXBYqoPKfewDZo1"                   # right part of the pair
# -------------------------------------------------------------------

# -------------------------------------------------------------------
# 🎤 1) ElevenLabs TTS
# -------------------------------------------------------------------
def tts_generate(text: str,
                 voice_id: str,
                 api_key: str) -> bytes:
    """Return MP3 bytes generated by ElevenLabs from the input text."""
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"
    headers = {
        "xi-api-key": api_key,
        "Accept": "audio/mpeg",
        "Content-Type": "application/json"
    }
    body = {
        "text": text,
        "model_id": "eleven_monolingual_v1",
        # Optional voice tweaks:
        "voice_settings": {
            "stability": 0.45,
            "similarity_boost": 0.75
        }
    }

    r = requests.post(url, json=body, headers=headers, timeout=60000)
    if r.status_code != 200:
        raise RuntimeError(f"ElevenLabs TTS failed → {r.status_code}: {r.text}")
    return r.content


# -------------------------------------------------------------------
# ⬆️ 2) Upload MP3 to D‑ID
# -------------------------------------------------------------------
def did_upload_audio(mp3_bytes: bytes,
                     filename: str,
                     auth: HTTPBasicAuth) -> str:
    """
    Upload audio to D‑ID and return the public/temporary audio_url.
    """
    url = "https://api.d-id.com/audios"
    files = {"audio": (filename, mp3_bytes, "audio/mpeg")}
    r = requests.post(url, files=files, auth=auth, timeout=60)
    # Fix: Check for 201 (Created) instead of 200
    if r.status_code != 201:
        raise RuntimeError(f"D‑ID upload failed → {r.status_code}: {r.text}")
    return r.json()["url"]          # 24‑48 h lifetime


# -------------------------------------------------------------------
# 🎬 3) Create talking‑avatar video
# -------------------------------------------------------------------
def did_create_video(audio_url: str,
                     image_or_presenter: dict,
                     auth: HTTPBasicAuth) -> str:
    """
    Kick off a D‑ID 'talk' and return the resulting video ID.
    `image_or_presenter` must contain either:
        {"source_url": "https://…jpg"}      OR
        {"presenter_id": "p-xxxxxxxx"}      OR
        {"driver_url": "https://…mp4"} (for live driver)
    """
    url = "https://api.d-id.com/talks"
    payload = {
        **image_or_presenter,
        "script": {
            "type": "audio",
            "audio_url": audio_url
        }
        # Optionally add config / stitch here
    }
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    r = requests.post(url, json=payload, auth=auth, headers=headers, timeout=60)
    # Fix: Check for 201 (Created) instead of 200
    if r.status_code != 201:
        raise RuntimeError(f"D‑ID create talk failed → {r.status_code}: {r.text}")
    return r.json()["id"]


# -------------------------------------------------------------------
# ⏳ 4) Poll until video is ready
# -------------------------------------------------------------------
def did_poll_video(video_id: str,
                   auth: HTTPBasicAuth,
                   timeout: int = 600,
                   poll_interval: int = 5) -> str:
    """Poll D‑ID until status=='done' and return result_url."""
    url = f"https://api.d-id.com/talks/{video_id}"
    start = time.time()
    while True:
        r = requests.get(url, auth=auth, timeout=30)
        if r.status_code != 200:
            raise RuntimeError(f"Polling failed → {r.status_code}: {r.text}")
        data = r.json()
        status = data.get("status")
        if status == "done":
            return data["result_url"]
        if status == "error":
            raise RuntimeError(f"D‑ID reported error: {data.get('error')}")
        if time.time() - start > timeout:
            raise TimeoutError(f"Timed out after {timeout} s.")
        time.sleep(poll_interval)


# -------------------------------------------------------------------
# 🚀 MAIN PIPELINE
# -------------------------------------------------------------------
if __name__ == "__main__":
    # 1) Text you want the avatar to say
    NEWS_TEXT = (
        "Good evening. Today's top stories include breakthrough developments "
        "in artificial intelligence and significant market movements. "
        "And the winner of today's AI competition is none other than WeShowSpeed!"
    )

    # 2) Choose an avatar – EITHER an image URL…
    AVATAR_INFO = {
        "source_url": "https://i.ibb.co/Xf0jZSKq/anchor-min.jpg"
    }
    # …OR a presenter already in your D‑ID account:
    # AVATAR_INFO = { "presenter_id": "p-1234567890abcdef" }

    auth = HTTPBasicAuth(DID_USERNAME, DID_PASSWORD)

    print("▶️  Generating speech with ElevenLabs…")
    mp3 = tts_generate(NEWS_TEXT, ELEVEN_VOICE_ID, ELEVEN_API_KEY)
    print(f"   ✔️  TTS complete – {len(mp3):,} bytes")

    print("⬆️  Uploading audio to D‑ID…")
    audio_url = did_upload_audio(mp3, "speech.mp3", auth)
    print(f"   ✔️  Audio URL: {audio_url}")

    print("🎞️  Creating avatar video…")
    video_id = did_create_video(audio_url, AVATAR_INFO, auth)
    print(f"   ✔️  Talk ID: {video_id}")

    print("⏳  Polling for completion…")
    result_url = did_poll_video(video_id, auth)
    print(f"\n✅  Video ready!\n🔗 {result_url}")